USE sangmin;

CREATE TABLE MEMBER(
	id VARCHAR(100) NOT NULL PRIMARY KEY,
	pw VARCHAR(300) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	tel VARCHAR(11),
	email VARCHAR(100),
	birth DATE,
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP());

INSERT INTO MEMBER(id, pw, NAME) VALUES("admin", "1234", "관리자");
INSERT INTO MEMBER(id, pw, NAME) VALUES("master", "1234", "관리자");
INSERT INTO MEMBER(id, pw, NAME) VALUES("visitor", "1234", "방문객");

COMMIT;